# Errors

load\_disease\_relation.sh ev\_drug.sh

interaction:

The index will have id {'with_retry': True, 'eshost': \('localhost:9200',\), 'bulksize': 5000, 'index': 'interaction', 'idfield': 'id', 'verifycerts': False, 'usessl': False, 'cacerts': None, 'httpauth': None, 'delete': False, 'update': False, 'progress': False, 'type': 'doc', 'aschild': False, 'indexsettingsfile': None, 'timeout': 10.0, 'encoding': 'utf-8', 'keys': \[\], 'esconn': } Traceback \(most recent call last\): File "/Users/jonkiky/opt/anaconda3/bin/elasticsearchloader", line 8, in  sys.exit\(cli\(\)\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 764, in **call** return self.main\(args, **kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 717, in main rv = self.invoke\(ctx\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1137, in invoke return \_process\_result\(sub\_ctx.command.invoke\(sub\_ctx\)\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 956, in invoke return ctx.invoke\(self.callback,** ctx.params\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 555, in invoke return callback\(args, **kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 17, in new\_func return f\(get\_current\_context\(\), \*args,** kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearchloader/**init**.py", line 150, in json load\(lines, ctx.obj\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearchloader/**init**.py", line 51, in load for i, bulk in enumerate\(pbar\): File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/termuiimpl.py", line 285, in generator for rv in self.iter: File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearchloader/iter.py", line 43, in jsonlinesiter yield json.loads\(line\) ValueError: Expected object or value /Users/jonkiky/Documents/work/openTarget/database//interactions/part-00001-a0adda2d-44b4-4c6d-b4d2-7fc069ccc687-c000.json The index will have id {'withretry': True, 'eshost': \('localhost:9200',\), 'bulk\_size': 5000, 'index': 'interaction', 'id\_field': 'id', 'verify\_certs': False, 'use\_ssl': False, 'ca\_certs': None, 'http\_auth': None, 'delete': False, 'update': False, 'progress': False, 'type': '\_doc', 'as\_child': False, 'index\_settings\_file': None, 'timeout': 10.0, 'encoding': 'utf-8', 'keys': \[\], 'es\_conn': } Traceback \(most recent call last\): File "/Users/jonkiky/opt/anaconda3/bin/elasticsearch\_loader", line 8, in  sys.exit\(cli\(\)\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 764, in \_\_call return self.main\(args, **kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 717, in main rv = self.invoke\(ctx\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1137, in invoke return \_process\_result\(sub\_ctx.command.invoke\(sub\_ctx\)\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 956, in invoke return ctx.invoke\(self.callback,** ctx.params\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 555, in invoke return callback\(args, **kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 17, in new\_func return f\(get\_current\_context\(\), \*args,** kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/\_\_init.py", line 150, in \_json load\(lines, ctx.obj\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/\_\_init.py", line 51, in load for i, bulk in enumerate\(pbar\): File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/\_termui\_impl.py", line 285, in generator for rv in self.iter: File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/iter.py", line 43, in json\_lines\_iter yield json.loads\(line\) ValueError: Expected object or value /Users/jonkiky/Documents/work/openTarget/database//interactions/part-00002-a0adda2d-44b4-4c6d-b4d2-7fc069ccc687-c000.json The index will have id {'with\_retry': True, 'es\_host': \('localhost:9200',\), 'bulk\_size': 5000, 'index': 'interaction', 'id\_field': 'id', 'verify\_certs': False, 'use\_ssl': False, 'ca\_certs': None, 'http\_auth': None, 'delete': False, 'update': False, 'progress': False, 'type': '\_doc', 'as\_child': False, 'index\_settings\_file': None, 'timeout': 10.0, 'encoding': 'utf-8', 'keys': \[\], 'es\_conn': } Traceback \(most recent call last\): File "/Users/jonkiky/opt/anaconda3/bin/elasticsearch\_loader", line 8, in  sys.exit\(cli\(\)\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 764, in \_\_call return self.main\(args, **kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 717, in main rv = self.invoke\(ctx\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1137, in invoke return \_process\_result\(sub\_ctx.command.invoke\(sub\_ctx\)\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 956, in invoke return ctx.invoke\(self.callback,** ctx.params\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 555, in invoke return callback\(args, **kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 17, in new\_func return f\(get\_current\_context\(\), \*args,** kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/\_\_init.py", line 150, in \_json load\(lines, ctx.obj\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/\_\_init.py", line 51, in load for i, bulk in enumerate\(pbar\): File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/\_termui\_impl.py", line 285, in generator for rv in self.iter: File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/iter.py", line 43, in json\_lines\_iter yield json.loads\(line\) ValueError: Expected object or value /Users/jonkiky/Documents/work/openTarget/database//interactions/part-00003-a0adda2d-44b4-4c6d-b4d2-7fc069ccc687-c000.json The index will have id {'with\_retry': True, 'es\_host': \('localhost:9200',\), 'bulk\_size': 5000, 'index': 'interaction', 'id\_field': 'id', 'verify\_certs': False, 'use\_ssl': False, 'ca\_certs': None, 'http\_auth': None, 'delete': False, 'update': False, 'progress': False, 'type': '\_doc', 'as\_child': False, 'index\_settings\_file': None, 'timeout': 10.0, 'encoding': 'utf-8', 'keys': \[\], 'es\_conn': } Traceback \(most recent call last\): File "/Users/jonkiky/opt/anaconda3/bin/elasticsearch\_loader", line 8, in  sys.exit\(cli\(\)\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 764, in \_\_call return self.main\(args, **kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 717, in main rv = self.invoke\(ctx\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1137, in invoke return \_process\_result\(sub\_ctx.command.invoke\(sub\_ctx\)\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 956, in invoke return ctx.invoke\(self.callback,** ctx.params\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 555, in invoke return callback\(args, **kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 17, in new\_func return f\(get\_current\_context\(\), \*args,** kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/\_\_init.py", line 150, in \_json load\(lines, ctx.obj\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/\_\_init.py", line 51, in load for i, bulk in enumerate\(pbar\): File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/\_termui\_impl.py", line 285, in generator for rv in self.iter: File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/iter.py", line 43, in json\_lines\_iter yield json.loads\(line\) ValueError: Expected object or value /Users/jonkiky/Documents/work/openTarget/database//interactions/part-00004-a0adda2d-44b4-4c6d-b4d2-7fc069ccc687-c000.json The index will have id {'with\_retry': True, 'es\_host': \('localhost:9200',\), 'bulk\_size': 5000, 'index': 'interaction', 'id\_field': 'id', 'verify\_certs': False, 'use\_ssl': False, 'ca\_certs': None, 'http\_auth': None, 'delete': False, 'update': False, 'progress': False, 'type': '\_doc', 'as\_child': False, 'index\_settings\_file': None, 'timeout': 10.0, 'encoding': 'utf-8', 'keys': \[\], 'es\_conn': } Traceback \(most recent call last\): File "/Users/jonkiky/opt/anaconda3/bin/elasticsearch\_loader", line 8, in  sys.exit\(cli\(\)\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 764, in \_\_call return self.main\(args, **kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 717, in main rv = self.invoke\(ctx\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1137, in invoke return \_process\_result\(sub\_ctx.command.invoke\(sub\_ctx\)\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 956, in invoke return ctx.invoke\(self.callback,** ctx.params\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 555, in invoke return callback\(args, **kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 17, in new\_func return f\(get\_current\_context\(\), \*args,** kwargs\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/\_\_init.py", line 150, in \_json load\(lines, ctx.obj\) File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/\_\_init_.py", line 51, in load for i, bulk in enumerate\(pbar\): File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/click/\_termui\_impl.py", line 285, in generator for rv in self.iter: File "/Users/jonkiky/opt/anaconda3/lib/python3.8/site-packages/elasticsearch\_loader/iter.py", line 43, in json\_lines\_iter yield json.loads\(line\) ValueError: Expected object or value

